name: currency_converter
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter
  http: ^1.3.0
  provider: ^6.1.2
  url_launcher: ^6.2.5
  firebase_core: ^3.12.1
  firebase_messaging: ^15.2.4
  shared_preferences: ^2.5.2
  dio: ^5.8.0+1
  flutter_local_notifications: ^19.0.0
  cloud_firestore: ^5.6.5
  firebase_auth: ^5.5.1
  fl_chart: ^0.70.2
  flutter_svg: ^2.0.17
  intl: ^0.20.2
  google_nav_bar: ^5.0.7
  cached_network_image: ^3.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

  

flutter:
  uses-material-design: true
  assets:
    - assets/
    - web/firebase-messaging-sw.js
