// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDZm6AqNJ234YW-NBxhy_xWjDGDy5o_vQQ',
    appId: '1:71306683320:android:976b731bac3d159038a54d',
    messagingSenderId: '71306683320',
    projectId: 'currencyconverter-2d61d',
    storageBucket: 'currencyconverter-2d61d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDUtNU_SznGN-xAMoxzWDpwgRdMw3RPnbE',
    appId: '1:71306683320:ios:c203890d8a9716a538a54d',
    messagingSenderId: '71306683320',
    projectId: 'currencyconverter-2d61d',
    storageBucket: 'currencyconverter-2d61d.firebasestorage.app',
    iosBundleId: 'com.example.currencyConverter',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB1VHXoiOan6z3XFfOLzRLfTC1PPVm8_Ro',
    appId: '1:71306683320:web:5a4ca4bc5c38642e38a54d',
    messagingSenderId: '71306683320',
    projectId: 'currencyconverter-2d61d',
    authDomain: 'currencyconverter-2d61d.firebaseapp.com',
    storageBucket: 'currencyconverter-2d61d.firebasestorage.app',
  );

}