// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCStg9Ab2RK3pK4xLl4s7TK9rgn5N41I5A',
    appId: '1:859088791503:web:790268b9199907f16b14ba',
    messagingSenderId: '859088791503',
    projectId: 'currency-conversion-hist-d28e7',
    authDomain: 'currency-conversion-hist-d28e7.firebaseapp.com',
    storageBucket: 'currency-conversion-hist-d28e7.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCe6MnJ4dT-qTFKdQ3lizk0Y0qMq1CuM2A',
    appId: '1:859088791503:android:ffe44eec866e46aa6b14ba',
    messagingSenderId: '859088791503',
    projectId: 'currency-conversion-hist-d28e7',
    storageBucket: 'currency-conversion-hist-d28e7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBZ-6ZbLvhOBrSNr1ryNwd3lto4bxzLZLY',
    appId: '1:859088791503:ios:ff36278b295a21e46b14ba',
    messagingSenderId: '859088791503',
    projectId: 'currency-conversion-hist-d28e7',
    storageBucket: 'currency-conversion-hist-d28e7.firebasestorage.app',
    iosBundleId: 'com.example.currencyConverter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBZ-6ZbLvhOBrSNr1ryNwd3lto4bxzLZLY',
    appId: '1:859088791503:ios:ff36278b295a21e46b14ba',
    messagingSenderId: '859088791503',
    projectId: 'currency-conversion-hist-d28e7',
    storageBucket: 'currency-conversion-hist-d28e7.firebasestorage.app',
    iosBundleId: 'com.example.currencyConverter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCStg9Ab2RK3pK4xLl4s7TK9rgn5N41I5A',
    appId: '1:859088791503:web:ac40c64342f9f3de6b14ba',
    messagingSenderId: '859088791503',
    projectId: 'currency-conversion-hist-d28e7',
    authDomain: 'currency-conversion-hist-d28e7.firebaseapp.com',
    storageBucket: 'currency-conversion-hist-d28e7.firebasestorage.app',
  );
}
